--- mono-2.10.8.1.orig/mcs/class/Makefile	2012-01-27 16:20:36.319297999 -0500
+++ mono-2.10.8.1/mcs/class/Makefile	2012-01-27 20:37:30.867593825 -0500
@@ -55,10 +55,8 @@
 	Novell.Directory.Ldap		\
 	Mono.Security.Win32		\
 	System.DirectoryServices	\
-	RabbitMQ.Client			\
 	Mono.Messaging			\
 	System.Messaging	        \
-	Mono.Messaging.RabbitMQ		\
 	System.ServiceProcess           \
 	System.Drawing.Design		\
 	System.Design			\
